version: '3'
services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      - postgres_db
      - keydb_db
    links:
      - keydb_db
      - postgres_db
    ports:
      - "80:80"
    expose:
      - "80"
    env_file:
      - ".env.web"
    command: gunicorn app:server --preload --workers=5 --threads=5 --worker-class gevent --timeout 300 --graceful-timeout 300 --max-requests 150 --log-level=info -b :80
  postgres_db:
    image: "postgres:latest"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    env_file:
      - ".env.db"
  keydb_db:
    image: "eqalpha/keydb"
    restart: always
    command: keydb-cli --bind keydb_db --requirepass ${KEYDB_PASSWORD} --maxmemory 256mb --maxmemory-policy volatile-ttl --appendonly yes --server-threads 4
volumes:
  postgres-data:
